import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('tABABguAIAHAwXPHh7BAAhSABAghCBAj8BvkAIADADADALAIAABAAHAQAIADADADALAw-2AAAAAAAAAAAAAg8ABAJAAAGAGAGAGABBIAAAAABBkjACBn8B4NXUkNBAAABJAAAABBCDjuAAAJMAEAAABABAI4NYOGhVF4SY-od');
